Update MANUAL, add UCS
rustyrazorblade/easy-cass-stress pull request #31
Opened 2024-09-09 18:48 UTC by george0st

Extend compaction list, add UCS

2024-09-09 18:54 UTC, rustyrazorblade requested changes
Thanks for the manual update.  Please see my comments.

2024-09-09 18:54 UTC, rustyrazorblade commented on manual/MANUAL.adoc
> +`{'class':'UnifiedCompactionStrategy', 'XXX':'L4'}`
This should be 

```
`{'class':'UnifiedCompactionStrategy', 'scaling_parameters':'L4'}`
```

2024-09-09 18:54 UTC, rustyrazorblade commented on manual/MANUAL.adoc
> +`{'class':'UnifiedCompactionStrategy', 'XXX':'L4', 'YYY':'L10'}`
This should be 

```
`{'class':'UnifiedCompactionStrategy', 'scaling_parameters':'L4,L10'}`
```

2024-09-09 19:55 UTC, merged

2024-09-09 19:55 UTC, rustyrazorblade commented
Thanks for the PR!

2024-12-14 18:23 UTC, jrwest commented
@george0st we are working to donate `easy-cass-stress` to the Apache foundation. Would you be willing to sign an [ICLA](https://apache.org/licenses/icla.pdf) and donate your contributions?